### ISSUE TITLE
Axes values with negative numbers are not properly displayed

### ISSUE THREAD

**Issue by Pepe-Marquez** [silx-kit/h5grove#59]
There seems to be a bug with the data displayed by h5web.  The axis positions are not properly placed.

Running on jupyter lab 3.2.9 and jupyterlab-h5web 1.3.0. 

The minimum and max values of the y axis (energy) are: −4.000e+0 to 1.000e+0
The minimum and max values of the x axis (delay) are: −2.000e+3 to 6.500e+3

![image](https://user-images.githubusercontent.com/64071335/152564153-8713950f-0aa9-4ef0-b7a6-aa0df0fb6309.png)

**Comment by Pepe-Marquez** [comment]
Moved this issue to h5web.

**Comment by andygotz** [comment]
@Pepe-Marquez which issue is it in h5web? I don't see any new issue.

**Comment by axelboc** [comment]
@andygotz it's in the `jupyterlab-h5web` repo: https://github.com/silx-kit/jupyterlab-h5web/issues/80
